# Generated by Django 3.2.9 on 2022-03-31 08:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('webdav', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharelink',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
