# Generated by Django 3.2.9 on 2022-04-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdav', '0002_alter_sharelink_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='action',
            field=models.CharField(choices=[('mv', '重命名'), ('upload_file', '上传'), ('comment', '评论')], max_length=200),
        ),
    ]
