version: '3'
services:
  webdav:
    image: bytemark/webdav
    ports:
      - "80:80"
    environment:
      TZ: Asia/Shanghai
      USERNAME: chen
      PASSWORD: orange0220
    volumes:
      - ./dav:/var/lib/dav
